spring:
  redis:
    host: localhost
    port: 7379
    password: eve_redis
    database: 1
    pool:
      max-active: 300
      max-idle: 100
      max-wait: 1000
      min-idle: 10
  datasource:
    url: jdbc:hsqldb:file:./db/eve
    username: zwei
    password: eve_data
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
server:
  port: 42081
security:
  basic:
    enabled: false
datasource:
  driverClassName: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:file:./db/eve
  username: zwei
  password: eve_data
  jmxEnabled: false
  testWhileIdle: false
  validationQuery: SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
  testOnBorrow: true
  testOnReturn: false
  validationInterval: 30000
  timeBetweenEvictionRunsMillis: 10000
  maxActive: 10
  maxIdle: 2
  minIdle: 1
  initialSize: 2
  maxWait: 60000
  removeAbandoned: true
  removeAbandonedTimeout: 60000
  minEvictableIdleTimeMillis: 60000
  logAbandoned: true
  cryptographic: false
business:
  watching-regions:
  - 10000002
  - 10000006
  - 10000012
global:
  executor-thread-count: 50
data:
  rebuild-database: false
  universe:
    eve:
    - file:fsd/universe/eve
    - file:eve_data/fsd/universe/eve
    wormhole:
    - file:fsd/universe/wormhole
    - file:eve_data/fsd/universe/wormhole
  blueprint:
  - file:fsd/blueprints.yaml
  - file:eve_data/fsd/blueprints.yaml
  type:
  - file:fsd/typeIDs.yaml
  - file:eve_data/fsd/typeIDs.yaml
sso: 
  endpoint: https://login.eveonline.com
  response-type: code
  redirect-uri: http://112.124.116.28/auth/callback/
  client-id: 95f8526a8b504f2bb3b95e650e609613
  secret-key: KsDHpjIu6qkyZQwZY7NgjpWdvfhf1SxKdL9Xfsvv
  state: ZH-CN
  request-verification-token: uZ_RBRlrmcogA4oRO8NkHEle3AZVa4PEstQ2RMWjNnhzU_q-fAERqvnNIxert0Yr3TYpyCiUqWNE4EScsQLIXGc-bJU1
  character-id: 2112814558
  authorization: Basic OTVmODUyNmE4YjUwNGYyYmIzYjk1ZTY1MGU2MDk2MTM6S3NESHBqSXU2cWt5WlF3Wlk3TmdqcFdkdmZoZjFTeEtkTDlYZnN2dg==
  interfaces: 
    auth:
      path: oauth/authorize
      method: POST
    token: 
      path: oauth/token
      method: POST
    refreshToken: 
      path: oauth/token
      method: POST
    obtainCharacter: 
      path: oauth/verify
      method: GET
  scopes:
  - corporationContactsRead
  - publicData
  - characterStatsRead
  - characterFittingsRead
  - characterFittingsWrite
  - characterContactsRead
  - characterContactsWrite
  - characterLocationRead
  - characterNavigationWrite
  - characterWalletRead
  - characterAssetsRead
  - characterCalendarRead
  - characterFactionalWarfareRead
  - characterIndustryJobsRead
  - characterKillsRead
  - characterMailRead
  - characterMarketOrdersRead
  - characterMedalsRead
  - characterNotificationsRead
  - characterResearchRead
  - characterSkillsRead
  - characterAccountRead
  - characterContractsRead
  - characterBookmarksRead
  - characterChatChannelsRead
  - characterClonesRead
  - characterOpportunitiesRead
  - characterLoyaltyPointsRead
  - corporationWalletRead
  - corporationAssetsRead
  - corporationMedalsRead
  - corporationFactionalWarfareRead
  - corporationIndustryJobsRead
  - corporationKillsRead
  - corporationMembersRead
  - corporationMarketOrdersRead
  - corporationStructuresRead
  - corporationShareholdersRead
  - corporationContractsRead
  - corporationBookmarksRead
  - fleetRead
  - fleetWrite
  - structureVulnUpdate
  - remoteClientUI
  - esi-calendar.respond_calendar_events.v1
  - esi-calendar.read_calendar_events.v1
  - esi-location.read_location.v1
  - esi-location.read_ship_type.v1
  - esi-mail.organize_mail.v1
  - esi-mail.read_mail.v1
  - esi-mail.send_mail.v1
  - esi-skills.read_skills.v1
  - esi-skills.read_skillqueue.v1
  - esi-wallet.read_character_wallet.v1
  - esi-wallet.read_corporation_wallet.v1
  - esi-search.search_structures.v1
  - esi-clones.read_clones.v1
  - esi-characters.read_contacts.v1
  - esi-universe.read_structures.v1
  - esi-bookmarks.read_character_bookmarks.v1
  - esi-killmails.read_killmails.v1
  - esi-corporations.read_corporation_membership.v1
  - esi-assets.read_assets.v1
  - esi-planets.manage_planets.v1
  - esi-fleets.read_fleet.v1
  - esi-fleets.write_fleet.v1
  - esi-ui.open_window.v1
  - esi-ui.write_waypoint.v1
  - esi-characters.write_contacts.v1
  - esi-fittings.read_fittings.v1
  - esi-fittings.write_fittings.v1
  - esi-markets.structure_markets.v1
  - esi-corporations.read_structures.v1
  - esi-corporations.write_structures.v1
  - esi-characters.read_loyalty.v1
  - esi-characters.read_opportunities.v1
  - esi-characters.read_chat_channels.v1
  - esi-characters.read_medals.v1
  - esi-characters.read_standings.v1
  - esi-characters.read_agents_research.v1
  - esi-industry.read_character_jobs.v1
  - esi-markets.read_character_orders.v1
  - esi-characters.read_blueprints.v1
  - esi-characters.read_corporation_roles.v1
  - esi-location.read_online.v1
  - esi-contracts.read_character_contracts.v1
  - esi-clones.read_implants.v1
  - esi-characters.read_fatigue.v1
  - esi-killmails.read_corporation_killmails.v1
  - esi-corporations.track_members.v1
  - esi-wallet.read_corporation_wallets.v1
  - esi-characters.read_notifications.v1
esi:
  languages:
  - zh
  - en-us
  endpoint: https://esi.tech.ccp.is/latest
  version: latest
  datasource: tranquility
  retry-count: 3
  total-page-key: X-Pages
  timeout: 180
  interfaces:
    region:
      path: universe/regions/{region_id}
      method: get
    constellation:
      path: universe/constellations/{constellation_id}
      method: get
    system:
      path: universe/systems/{system_id}
      method: get
    star:
      path: universe/star/{star_id}
      method: get
    planet:
      path: universe/planets/{planet_id}
      method: get
    moon:
      path: universe/moons/{moon_id}
      method: get
    type:
      path: universe/types/{type_id}
      method: get
    group:
      path: universe/groups/{group_id}
      method: get
    orders:
      path: markets/{region_id}/orders
      method: get